theme = "catppuccin_mocha"

[editor]
color-modes = true
cursorline = true
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
